-- MySQL Script generated by MySQL Workbench
-- seg 15 jun 2020 14:13:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Processador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Processador` (
  `nome` VARCHAR(40) NOT NULL,
  `clock` DOUBLE NULL,
  `thread` DOUBLE NULL,
  `tdp` DOUBLE NULL,
  `soquete` VARCHAR(10) NULL,
  `cache` DOUBLE NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ram` (
  `nome` VARCHAR(40) NOT NULL,
  `velocidade` INT NULL,
  `tamanho` INT NULL,
  `ddr` INT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
